### ISSUE TITLE
程序识别结果与原文线段划分图的对比

### ISSUE THREAD

**Issue by zengbin93** [waditu/czsc#12]
利用业余时间用 python 实现了缠论的主要逻辑，代码已开源至 github：[https://github.com/zengbin93/czsc](https://github.com/zengbin93/czsc)

**说明：** 在没有正式介绍分型、笔、线段的划分标准之前，博客原文线段划分并没有严格按照定义来。所以，前面的识别结果重合率较低。

### 2007-05-31 22:35 教你炒股票57：当下图解分析再示范
---
[http://blog.sina.com.cn/s/blog_486e105c01000ax3.html](http://blog.sina.com.cn/s/blog_486e105c01000ax3.html)
![原文划分](https://upload-images.jianshu.io/upload_images/4604328-ddf3323688e899dc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-a756db3b29d0f61c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-04 22:34 教你炒股票58：图解分析示范三
---
[http://blog.sina.com.cn/s/blog_486e105c01000az8.html](http://blog.sina.com.cn/s/blog_486e105c01000az8.html)

![原文划分](https://upload-images.jianshu.io/upload_images/4604328-a78a76830e10b7bc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-89161d1f79ea1c86.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-14 08:23 教你炒股票59：图解分析示范四
---
[http://blog.sina.com.cn/s/blog_486e105c01000b52.html](http://blog.sina.com.cn/s/blog_486e105c01000b52.html)

![原文划分1](https://upload-images.jianshu.io/upload_images/4604328-8ba213ec4ede278a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别1](https://upload-images.jianshu.io/upload_images/4604328-c1ed6835bab0ecaa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![原文划分2](https://upload-images.jianshu.io/upload_images/4604328-47c851c487a4730c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别2](https://upload-images.jianshu.io/upload_images/4604328-9dd276596fc420fb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![原文划分3](https://upload-images.jianshu.io/upload_images/4604328-b3d0f19493b140a8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别3](https://upload-images.jianshu.io/upload_images/4604328-b50bca997c63cff7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-19 08:04 教你炒股票60：图解分析示范五
---
[http://blog.sina.com.cn/s/blog_486e105c01000b83.html](http://blog.sina.com.cn/s/blog_486e105c01000b83.html)

![原文划分](https://upload-images.jianshu.io/upload_images/4604328-d70d21588744ff06.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-12bf20115fafe4e6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-21 08:13 教你炒股票61：区间套定位标准图解（分析示范六）
---
[http://blog.sina.com.cn/s/blog_486e105c01000b9n.html](http://blog.sina.com.cn/s/blog_486e105c01000b9n.html)

![原文划分](https://upload-images.jianshu.io/upload_images/4604328-48b1c74934e98e56.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-420ff2bd932db572.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-28 15:53 一根筋是不适合玩震荡行情的
---
[http://blog.sina.com.cn/s/blog_486e105c01000bdx.html](http://blog.sina.com.cn/s/blog_486e105c01000bdx.html)

![原文划分](https://upload-images.jianshu.io/upload_images/4604328-5ea5a1bbb4a15d0e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-cff3e1ff79e8417f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2007-06-29 15:45 解盘并说说中短线走势
---
[http://blog.sina.com.cn/s/blog_486e105c01000beh.html](http://blog.sina.com.cn/s/blog_486e105c01000beh.html)

![原文划分](https://upload-images.jianshu.io/upload_images/4604328-edfc50bc1ee5d0c5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![程序识别](https://upload-images.jianshu.io/upload_images/4604328-b87e28d5f94a1375.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by jackyq2015** [comment]
能不能写个简单的教程，怎么生成上面的图片的？
还有，中枢可以画出来吗？看到有个find_zs（）
