### ISSUE TITLE
如果没有掘金终端，对应的功能如何替代。

### ISSUE THREAD

**Issue by NoraGithub** [waditu/czsc#123]
mac用户，本项目入门阶段。从视频和代码阅读来看，感觉和掘金终端耦合的部分不少。
请问依赖掘金终端的功能有办法用其他方式实现吗？

例如，
examples/gm_backtest.py 使用掘金终端进行缠论策略回测
examples/gm_realtime.py 使用掘金终端进行策略实盘、仿真
examples/gm_check_point.py 使用掘金终端的数据进行买卖点验证

这些。
看提交记录，感觉qmt可能和掘金都属于connector？将来是有什么计划吗？以及对于mac设备都不太友好，有什么建议吗

**Comment by zengbin93** [comment]
mac 不适合做股票相关的，期货是可以的。可以考虑弄个windows机器或者开个云服务器

**Comment by NoraGithub** [comment]
基于这个判断，我开个虚拟机吧。这俩建议成本都有点高，哈哈。
mac的确没多少资源支持量化，特别是国内，判断大概率是对的。

> mac 不适合做股票相关的，期货是可以的。可以考虑弄个windows机器或者开个云服务器
