### ISSUE TITLE
代码理解

### ISSUE THREAD

**Issue by NoraGithub** [waditu/czsc#135]
https://github.com/waditu/czsc/blob/6d9d861239351a0d32e803a6079bc8d000a1b4e3/czsc/objects.py#L542

这里是否应该返回True,None

因为signal 都符合预期，如果没有factors，认为是match的？

**Comment by NoraGithub** [comment]
```python
        # 判断因子是否满足，顺序遍历，找到第一个满足的因子就退出
        # 因子放入事件中时，建议因子列表按关注度从高到低排序
        for factor in self.factors:
            if factor.is_match(s):
                return True, factor.name
            return False, None

        return True, None
```

这里的factors只能且是么，有点不理解设计的意图。

这里设计是希望factors必填么

**Comment by zengbin93** [comment]
factors 必填，最原始的用法是 factor 是 signal 的组合，event 是 factor 的组合。但是实践中发现，factors 里面会有很多重复的signal，所以在 event 里面又加入了一些 signals 填写，用于减少重复 signals 的填写
