### ISSUE TITLE
get_signals_config解析信号错误

### ISSUE THREAD

**Issue by Mjzs12138** [waditu/czsc#155]
使用get_signals_config解析czsc项目中已有信号，发现有几个信号解析错误:

解析信号 60分钟_K线_结束_否_任意_任意_0 - bar_end_V221211 - {freq}_{freq1}结束_BS辅助221211 出错：'NoneType' object has no attribute 'named'
解析信号 60分钟_K线_结束_是_任意_任意_0 - bar_end_V221211 - {freq}_{freq1}结束_BS辅助221211 出错：'NoneType' object has no attribute 'named'
解析信号 日线_D1ATR5T30突破_BS辅助V230424_看空_任意_任意_0 - tas_atr_break_V230424 - {freq}_D{di}通道突破#{N}#{K1}#{K2}_BS辅助V230403 出错：'NoneType' object has no attribute 'named'
解析信号 日线_D1ATR5T30突破_BS辅助V230424_看多_任意_任意_0 - tas_atr_break_V230424 - {freq}_D{di}通道突破#{N}#{K1}#{K2}_BS辅助V230403 出错：'NoneType' object has no attribute 'named'

**Comment by zengbin93** [comment]
@Mjzs12138 感谢纠错。0.9.23 已经修复了这两个问题
