### ISSUE TITLE
k线合并有个问题

### ISSUE THREAD

**Issue by CtaKing** [waditu/czsc#160]
![wecom-temp-f404f073a73d44412d9cd957a6dc496d](https://github.com/waditu/czsc/assets/91359542/727aa942-8db5-4fd3-88c6-09237cb59a68)

这种情况的k线合并有想过特殊处理一下吗？

**Comment by CtaKing** [comment]
我以上面的k线举例，按照定义确实是向下合并，但是合并的这根k线其实是比前面的顶分型高了，向下合并有可能会导致向上笔的终点在前面的那个顶分型，其实这根k线是破坏了前面的顶分型的，只是向下合并的时候把最高价舍弃了。

**Comment by zengbin93** [comment]
如果你认为你的理解是对的，你可以按照这种方法修改对应的代码
