### ISSUE TITLE
代码中一个语法问题，百度不到，请帮忙解决一下，谢谢

### ISSUE THREAD

**Issue by baydragons** [waditu/czsc#69]
analyze.py文件中234、235行    
  for bar in bars:
            self.update(bar)
这个语句self直接update这个用法从来没看见过，能否告知是什么原理或者有什么参考文章，谢谢！

**Comment by vercity** [comment]
> 

analyze  303行

**Comment by baydragons** [comment]
> > 
> 
> analyze 303行
非常感谢
