### ISSUE TITLE
因特殊分型导致笔识别失败

### ISSUE THREAD

**Issue by 363617763** [waditu/czsc#70]
SHFE.hc2201  期货热轧
数据周期：1分钟
时间: 2021-11-25  13:00  ——2021-11-26 10:00  
出现问题：因为一个特殊巨型分型，导致笔识别错误，已生成笔回撤，无法生成新的笔，具体如下 
![image](https://user-images.githubusercontent.com/83622407/143772834-78fc0f55-f924-4dff-8488-6f62ecd46255.png)

出错位置
![image](https://user-images.githubusercontent.com/83622407/143772938-8e4beeb4-1885-4601-be53-d89e14910efd.png)

使用0.71版本中  check_fx 替换之后可以正常
![image](https://user-images.githubusercontent.com/83622407/143772885-b452cbb9-0ace-4406-9867-07aa0e068c07.png)

**Comment by zengbin93** [comment]
这个问题主要是未完成笔的回溯机制回影响到最近两个已完成笔造成的。今天评估了一下，未完成笔的回溯机制如果只影响最近一个已完成的笔，会有一些笔的高低点不在最高、最低的位置，但整体影响不大，且更合理。这个问题在 0.8.8 版本修复
