### ISSUE TITLE
回测过程中的止损止盈？

### ISSUE THREAD

**Issue by ylrh333** [waditu/czsc#78]
回测的时候，当日线三买出现后买入，买入后跌5%卖出，涨10%也卖出。这个止损止盈的因子该怎么写？有没有可以参考的例子？谢谢。

**Comment by ylrh333** [comment]
应该是这个止损止盈的信号该怎么写？咱们的系统有没有可以参考的例子

**Comment by ylrh3** [comment]
在check_signal_acc里这么编写，但是为啥
程序只运行到   print('dd1')
然后就卡在下边这一句了，信号形成不了，大佬知道是为啥吗？求指教一二，谢谢。
 v = Signal(k1=k1, k2=f"倒1K", k3="出信号后涨跌幅", v1="下跌5%")



signals = [
    Signal("日线_倒1k_出信号后涨跌幅_下跌5%_任意_任意_0"),
    Signal("日线_倒1k_出信号后涨跌幅_上涨20%_任意_任意_0"),
]

def get_wj_signals(c: CZSC) -> OrderedDict:
    """在 CZSC 对象上计算选股信号

    :param c: CZSC 对象
    :return: 信号字典
    """
    freq: Freq = c.freq
    s = OrderedDict({"symbol": c.symbol, "dt": c.bars_raw[-1].dt, "close": c.bars_raw[-1].close})

    if c.freq == Freq.D:
        s.update(get_s_like_bs(c, di=1))
    if c.freq == Freq.D:
        s.update(get_s_single_k(c, 1))

    default_signals = [
        # 以下是技术指标相关信号
        Signal(k1=str(freq.value), k2="倒1K", k3="出信号后涨跌幅", v1="其他", v2='其他', v3='其他'),
    ]
    for signal in default_signals:
        s[signal.key] = signal.value

    if not c.bi_list:
        return s
    if len(c.bars_raw) < 2:
        return s
    k=c.bars_raw
    klen=len(c.bars_raw)
    print('dd')
    if Signal("日线_倒1笔_类买卖点_类三买_任意_任意_0"):
        if (k[-1].close-k[-klen].close)/k[-klen].close < -0.05 :
            print('dd1')
            v = Signal(k1=k1, k2=f"倒1K", k3="出信号后涨跌幅", v1="下跌5%")
            s[v.key] = v.value
            print('x%s'%k)
        elif (k[-1].close-k[-klen].close)/k[-klen].close > 0.2 :
            v = Signal(k1=k1, k2=f"倒1K", k3="出信号后涨跌幅", v1="上涨20%")
            s[v.key] = v.value
            print('dd2')

    return s


if __name__ == '__main__':
    # 程序开始时的时间
    time_start = time.time()
    # 读入股票代码
               .
               .
               .
               .
               .
               .
    check_signals_acc(f60_raw_bars, signals, freqs=['日线','周线'], get_signals=get_wj_signals)
    # 程序结束时系统时间
    time_end = time.time()
    print('程序所耗时间：', time_end - time_start)



运行结果

dd
dd1
程序所耗时间： 1.817012071609497

**Comment by zengbin93** [comment]
@ylrh333 没有止盈止损逻辑，可以通过因子控制的能搞不能搞来实现

**Comment by zengbin93** [comment]
> if Signal("日线_倒1笔_类买卖点_类三买_任意_任意_0"):
>     if (k[-1].close-k[-klen].close)/k[-klen].close < -0.05 :

这里的逻辑都是错的，自己检查一下
