### ISSUE TITLE
潜在三买信号，如何在check_signal_acc里边调用呢？有无案例看看。谢谢

### ISSUE THREAD

**Issue by ylrh3** [waditu/czsc#79]
这样写，为啥调用不了潜在三买？

signals = [
    Signal("日线_倒0笔_潜在三买_构成中枢_近3K在中枢上沿附近_任意_0"),
]
def get_signals(c: CZSC) -> OrderedDict:
    s = OrderedDict({"symbol": c.symbol, "dt": c.bars_raw[-1].dt, "close": c.bars_raw[-1].close})
    s.update(get_s_d0_bi(c))
    s.update(get_s_three_k(c, 1))
    s.update(get_s_di_bi(c, 1))
    s.update(get_s_macd(c, 1))
    s.update(get_s_single_k(c, 1))
    s.update(get_s_bi_status(c))
    for di in range(1, 8):
        s.update(get_s_three_bi(c, di))

    for di in range(1, 8):
        s.update(get_s_base_xt(c, di))

    for di in range(1, 8):
        s.update(get_s_like_bs(c, di))
    return s

**Comment by zengbin93** [comment]
@ylrh3 你要自己先把潜在三买封装成一个独立的信号函数，然后调用。想搞量化，先学好python
