### ISSUE TITLE
关于出现连续同类型分型的问题

### ISSUE THREAD

**Issue by skyblue2001** [waditu/czsc#81]
代码analyze.py中第80行代码出现的连续同类型分型的问题，本质原因是在第211行代码
bars_ubi_a = last_bi.bars + [x for x in bars_ubi if x.dt > last_bi.bars[-1].dt]这里出现的问题
因为最后一笔的最后一个分型的最后一个无包含bar其实并没有真实完成，如果后面出现的k bar和这个bar包含了，原代码是不会处理的，这样就会漏掉这个K bar。正确的做法可以是：
bars_ubi_a = last_bi.bars[:-1] + [x for x in bars_ubi if x.dt > last_bi.bars[-2].dt]
因为在未成笔的不包含bar中，是处理了包含关系的，所以要舍弃最后一笔最后一个bar

**Comment by zengbin93** [comment]
@skyblue2001 多谢指明BUG，已修正
