### ISSUE TITLE
有交流群吗？微信或者QQ的

### ISSUE THREAD

**Issue by 232040337** [waditu/czsc#9]

**Comment by zengbin93** [comment]
@232040337 加微信 `zengbin93`，拉你入群

**Comment by kaien1226** [comment]
df = ts.pro_bar(ts_code=ts_code, freq=freq, start_date=start_date, end_date=end_date,adj='qfq', asset=asset)
抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

是因为我的账号积分不够吗？我目前650的积分
