### ISSUE TITLE
这种情况下，两根K构成一笔，是否正确。

### ISSUE THREAD

**Issue by rabbit666666** [waditu/czsc#92]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/525541/177678165-ba83f683-9ee8-4c11-9c45-a35c03e7069f.png">

倒数第4笔，由两根K线组成。但从K线数来说构不成笔的。

**Comment by chzhshch-new** [comment]
代码与时间。

**Comment by zengbin93** [comment]
@rabbit666666 按原文，这里肯定是不够成笔。如果要按原文画笔，环境变量参数相应的要调整

**Comment by rabbit666666** [comment]
谢谢回复。请问，是“ czsc_min_bi_len”参数吗？我是用的是默认的“6”，绘制结果就是上面的图。

请问，是不是还有别的参数？

**Comment by rabbit666666** [comment]
我用的是BTCUSDT的数据，4小时数据，这两根K线是：2022-7-01 4:00～8:00和 2022-7-01 8:00～12:00，时区是UTC+8.

做的修改：
1：代码我就是用的quick_start.py的示例代码，把获取的数据转换成了RawBar。
2：模拟F60，增加了一个F240的频率。
3.：针对F240，增加了4小时间隔的时刻。

其余的就没了。

**Comment by Inblac** [comment]
新版czsc增加了涨跌幅度条件成笔，不是原文的条件。
bi_change_th ，看环境变量定义  https://github.com/waditu/czsc/blob/master/czsc/envs.py
